version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    privileged: true
    environment:
      - DOCKER_HOST=tcp://dind:2375
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
    depends_on:
      - dind

  dind:
    image: docker:stable-dind
    privileged: true
    volumes:
      - dind_data:/var/lib/docker
    ports:
      - "2375:2375"

volumes:
  jenkins_data:
  dind_data:
